### ISSUE TITLE
key opacity does not work for image type areas

### ISSUE THREAD

**Issue by hysrx** [interestingimages/PrintingPress#1]
### Dysfunctional Opacity Manipulation

File: [`/src/PrintingPress/printingpress.py (2d68704)`](https://github.com/InterestingSystems/PrintingPress/blob/2d6870445a64ab52582f80bcb9eabcde78fa3145/src/PrintingPress/printingpress.py)

```python
334
335            Internals.print_if('  Adjusting image...', end='\r', condition=suppress)
336            # Change Image Opacity
337            area_image.putalpha(area_data.opacity)
338
339            # Rotate Image
340            area_image = area_image.rotate(area_data.rotation, expand=True)
341            Internals.print_if('  Adjusting image... DONE', condition=suppress)
342
```

The [PIL.Image.Image.putalpha](https://pillow.readthedocs.io/en/stable/reference/Image.html#PIL.Image.Image.putalpha) method is used for controlling transparency - as dictated in many online guides. Yet this does not change the opacity of the resulting image.

**Comment by hentai-chan** [comment]
This is just a wild guess, but have you seen [this thread](https://stackoverflow.com/questions/55021088/image-does-not-change-when-adding-an-alpha-channel) yet? The answer on SO points to [this issue](https://github.com/python-pillow/Pillow/issues/3695) which might be what you are looking for.

**Comment by hysrx** [comment]
> 
> 
> This is just a wild guess, but have you seen [this thread](https://stackoverflow.com/questions/55021088/image-does-not-change-when-adding-an-alpha-channel) yet? The answer on SO points to [this issue](https://github.com/python-pillow/Pillow/issues/3695) which might be what you are looking for.

I have seen the thread, but I am not trying to show the image. The thread did mention something about JPG files - so I may look further into that as I am testing with JPG files.
